plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: "/"


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "liyun's blog"
email: talonley3@gmail.com
description: "不积跬步，无以至千里；不积小流，无以成江海"
github:
  username: tsmliyun
swiftype:
  searchId:
gitment:
    repo:
    client_id:
    client_secret:

url: "https://tsmliyun.github.io"
imgrepo: "https://tsmliyun.github.io/static/img"

baidu_analysis: 5932d0c7a37693b1f46d0ed14571f61e






