# Site settings
name: liyun blog
email: 747271667@qq.com
author: liyun
url: https://tsmliyun.github.io/
resume_site: https://tsmliyun.github.io/Resume.io/
github: https://github.com/tsmliyun
baseurl: "/"
description: Action is the only road to knowledge.
meta_description: 不积跬步，无以至千里；不积小流，无以成江海
motto: Do one thing at a time, and do well.
banner: 一期一会

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liyun

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

